name: zxspectrum
description: Emulator for a Sinclair ZX Spectrum, a popular 8-bit home computer of the 1980s
version: 0.0.1
repository: https://github.com/timsneath/zxspectrum

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dart_z80: ^0.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  dart_z80:
    path: ../z80