name: zxspectrum
description: Emulator for a Sinclair ZX Spectrum, a popular 8-bit home computer of the 1980s
version: 0.0.4
repository: https://github.com/timsneath/zxspectrum

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dart_z80: ^0.0.5
  ffi: ^2.0.1
  ffigen: ^6.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5

ffigen:
  name: 'libz80'
  description: 'Bindings to the libz80 emulator core.'
  output: 'lib/src/libz80.dart'
  headers:
    entry-points:
     - 'libz80/z80.h'
  preamble: |
    // ignore_for_file: camel_case_types, non_constant_identifier_names, unused_field, unused_element, constant_identifier_names

dependency_overrides:
  dart_z80:
    path: ../z80